apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: no-latest-tag
spec:
  background: false
  rules:
    - name: deny-latest-tag
      match:
        any:
        - resources:
            kinds:
              - Deployment
      validate:
        failureAction: Enforce
        message: "Using image tag 'latest' is not allowed for security reasons."
        foreach:
        - list: "request.object.spec.template.spec.containers[]"
          deny:
            conditions:
              any:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "*:latest"
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "latest"
        - list: "request.object.spec.template.spec.initContainers[]"
          deny:
            conditions:
              any:
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "*:latest"
                - key: "{{ element.image }}"
                  operator: Equals
                  value: "latest"
