apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-imagepullpolicy-always
spec:
  background: false
  rules:
    - name: check-imagepullpolicy
      match:
        any:
        - resources:
            kinds:
              - Deployment
      validate:
        failureAction: Enforce
        message: "All containers must have imagePullPolicy set to Always."
        foreach:
        - list: "request.object.spec.template.spec.containers[]"
          deny:
            conditions:
              any:
                - key: "{{ element.imagePullPolicy == null }}"
                  operator: Equals
                  value: true
                - key: "{{ element.imagePullPolicy }}"
                  operator: NotEquals
                  value: "Always"
