apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-privileged-root-containers
spec:
  background: false
  rules:
    - name: deny-privileged-or-root-any-container
      match:
        any:
        - resources:
            kinds:
              - Deployment
      validate:
        failureAction: Enforce
        message: "Containers must not be privileged, run as root, or allow privilege escalation"
        foreach:
        - list: "request.object.spec.template.spec.containers[]"
          deny:
            conditions:
              any:
                - key: "{{ element.securityContext.privileged }}"
                  operator: Equals
                  value: true
                - key: "{{ element.securityContext.runAsNonRoot }}"
                  operator: Equals
                  value: false
                - key: "{{ element.securityContext.allowPrivilegeEscalation }}"
                  operator: Equals
                  value: true
