FROM python:3.11-slim-buster

WORKDIR /app

COPY backend/requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_APP=backend.app
ENV FLASK_ENV=production
ENV PYTHONUNBUFFERED=1

EXPOSE 5000

RUN useradd -m myuser
USER myuser

CMD ["python3", "-u", "backend/app.py"]
