name: PR-Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  precommit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r backend/requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  kube-linter-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run KubeLinter scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: k8s

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install test dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests
        run: pytest -v
