name: PR-Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  precommit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -r backend/requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

  kube-linter-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run KubeLinter scan
        uses: stackrox/kube-linter-action@v1
        with:
          directory: k8s/manifests

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install test dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests
        run: pytest -v

  container-image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "yash301998/flask-weather-app:latest"
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          vuln-type: "os,library"


  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        run: bandit -r backend/ -ll -iii -o bandit-report.txt
