name: Pre-Commit Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      # Step 3: Install pre-commit and dependencies
      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      # Step 4: Run pre-commit checks
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
